### ISSUE TITLE
Add support for instanced pipelines.

### ISSUE THREAD

**Issue by dumptruckman** [homedepot/github-webhook-resource#29]
# Change Request
## Tell us about your environment
* **Concourse version:** 7.4.1
* **github-webhook-resource version:** 1.1.5

## Describe your change request
**The problem you want to solve:**
For pipelines using instances variables (instanced pipelines), this resource does not set up working webhooks. You need to append query params for each instance variable in the form of `&var.some-var="someval"`.

**Your take on the correct solution to problem:**
Ideally the resource will automatically populate all instance variables in this way. An alternative is having a `vars` attribute that can be manually populated in the pipeline script; however, if any vars are forgotten in this manual way then I don't think the webhook will work.

**Do you plan to submit a pull request to implement this change?**
I may try if I can find the time to do so.

**Comment by GavinFigueroa** [comment]
Resolved in #30
